const mongoose=require('mongoose');
// const { object } = require('underscore');
const ProductSchema = new mongoose.Schema({
    name: {
        type:String,
        required:true
    },
    category:{
        type:String,
        required:true
    },
    seller_details:[{
        name_of_seller:{
            type:String,
            unique:true
        },
        company_name:{
            type:String,
        },
        location:{
            type:String,
        },
        phone_no:{
            type:Number,
        },
        email:{
            type:String,
        },
        inventory:[
            {
                color:{
                    type:String,
                },
                quantity:{
                    type:Number,
                    default:0
                }
            }
        ]
    }],
    global_inventory:[
        {
            color:{
                type:String,
            },
            quantity:{
                type:Number,
                default:0
            }
        }
    ],
    rating:[{
        user:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"user"
        },
        rating_star:{
            type:Number,
        },
        photo:{
            type:String,
        },
        comments:[
            {
                message:{
                    type:String,
                },
                user:{
                    type:mongoose.Schema.Types.ObjectId,
                    ref:"user"
                }
            }
        ]      
    }],
    description:{
        type:String
    },
    photos:[String]
});

module.exports=mongoose.model('product',ProductSchema);